### ISSUE TITLE
rest980 won't run on Homeassistant OS.

### ISSUE THREAD

**Issue by generalk25** [jeremywillans/hass-addons#6]
> rest980@2.1.0 start /usr/src/app
> node ./bin/www
/usr/src/app/node_modules/dorita980/lib/v2/cloud.js:7
  throw new Error('Not implemented.');
  ^
Error: Not implemented.
    at dorita980 (/usr/src/app/node_modules/dorita980/lib/v2/cloud.js:7:9)
    at new cloud (/usr/src/app/node_modules/dorita980/index.js:12:10)
    at /usr/src/app/routes/api.js:33:46
    at handleIP (/usr/src/app/routes/api.js:26:68)
    at Object.<anonymous> (/usr/src/app/routes/api.js:27:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/app.js:11:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/bin/www:7:11)
    at Module._compile (module.js:577:32)
npm ERR! Linux 5.10.42
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! rest980@2.1.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rest980@2.1.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rest980 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rest980
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rest980
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by jeremywillans** [comment]
Make sure firmware version is set to 2 (implies 2+)

**Comment by generalk25** [comment]
Dumbest thing in the world to ever get stuck on. Thanks that fixed it.

Hey in your directions by chance i couldn't how I check what port im supposed to be on for the web UI? and how i check it. I see the URL, and is the ip the IP of the home assistant OS?

**Comment by jeremywillans** [comment]
It dosent really matter what port you use, as long as you reference the same one in your configuration.

In the examples I use 3000 for rest980 and 3001 for php-nginx.

**Comment by generalk25** [comment]
at the HA address? same as the host OS?

**Comment by generalk25** [comment]
Because when i try to load the HA address it gives me a 404 on 3001.

404 Not Found
------------------------------

nginx/1.16.1

 Though it pulls a text page when i access port 3000.

**Comment by generalk25** [comment]
ignore that, figured that out, i'll let you know if I have issues with
other things.

**Comment by jeremywillans** [comment]
Glad you got it working 👍
